version: 2

locations:
  synology-photo:
    from:
      - /mnt/Synology-ydh
      - /mnt/Synology-Anne
      - /mnt/Synology-Dirk
      - /mnt/Synology-Sandra
      - /mnt/administratie
      - /mnt/Synology-Shared
    to: local

    copy:
      local: hetzner

    hooks: 
      prevalidate: 
        - sshfs -o IdentityFile=/home/ydh/.ssh/restic_backup_nas_hetzner restic_backup@172.16.3.2:/homes/YDH/Photos /mnt/Synology-ydh -o allow_other,default_permissions
        - sshfs -o IdentityFile=/home/ydh/.ssh/restic_backup_nas_hetzner restic_backup@172.16.3.2:/homes/Anne/Photos /mnt/Synology-Anne -o allow_other,default_permissions
        - sshfs -o IdentityFile=/home/ydh/.ssh/restic_backup_nas_hetzner "restic_backup@172.16.3.2:/homes/Dirk De Herdt/Photos" /mnt/Synology-Dirk -o allow_other,default_permissions
        - sshfs -o IdentityFile=/home/ydh/.ssh/restic_backup_nas_hetzner "restic_backup@172.16.3.2:/homes/Sandra Verheyen/Photos" /mnt/Synology-Sandra -o allow_other,default_permissions
        - sshfs -o IdentityFile=/home/ydh/.ssh/restic_backup_nas_hetzner restic_backup@172.16.3.2:/photo/ /mnt/Synology-Shared -o allow_other,default_permissions
        - sshfs -o IdentityFile=/home/ydh/.ssh/restic_backup_nas_hetzner restic_backup@172.16.3.2:/Administratie /mnt/administratie -o allow_other,default_permissions
      
      success:
        - echo "success"

      failure: 
        - echo "failure"


backends:
  hetzner:
    type: sftp
    path: storagebox:resticPhoto
    requirekey: true

  local:
    type: local
    path: /media/data/local