version: 2

locations:
  synology-photo:
    from:
      - /mnt/Synology-ydh
      - /mnt/Synology-Anne
      - /mnt/Synology-Dirk
      - /mnt/Synology-Sandra
      - /mnt/administratie
      - /mnt/Synology-Shared
    to: local

    copy:
      local: hetzner

    hooks: 
      prevalidate: 
        - sshfs -o IdentityFile=/home/ydh/.ssh/restic_backup_nas_hetzner restic_backup@172.16.3.2:/homes/YDH/Photos /mnt/Synology-ydh -o allow_other,default_permissions
        - sshfs -o IdentityFile=/home/ydh/.ssh/restic_backup_nas_hetzner restic_backup@172.16.3.2:/homes/Anne/Photos /mnt/Synology-Anne -o allow_other,default_permissions
        - sshfs -o IdentityFile=/home/ydh/.ssh/restic_backup_nas_hetzner "restic_backup@172.16.3.2:/homes/Dirk De Herdt/Photos" /mnt/Synology-Dirk -o allow_other,default_permissions
        - sshfs -o IdentityFile=/home/ydh/.ssh/restic_backup_nas_hetzner "restic_backup@172.16.3.2:/homes/Sandra Verheyen/Photos" /mnt/Synology-Sandra -o allow_other,default_permissions
        - sshfs -o IdentityFile=/home/ydh/.ssh/restic_backup_nas_hetzner restic_backup@172.16.3.2:/photo/ /mnt/Synology-Shared -o allow_other,default_permissions
        - sshfs -o IdentityFile=/home/ydh/.ssh/restic_backup_nas_hetzner restic_backup@172.16.3.2:/Administratie /mnt/administratie -o allow_other,default_permissions

      before:
        - 'curl -m 10 --retry 5 -X POST -H "Content-Type: text/plain" --data "Starting backup for location: ${AUTORESTIC_LOCATION}" https://<healthchecks-url>/ping/<uid>/start'
      
      success:
        - 'curl -m 10 --retry 5 -X POST -H "Content-Type: text/plain" --data "Backup successful for location: ${AUTORESTIC_LOCATION}" https://<healthchecks-url>/ping/<uid>'

      failure: 
        - 'curl -m 10 --retry 5 -X POST -H "Content-Type: text/plain" --data "Backup failed for location: ${AUTORESTIC_LOCATION}" https://<healthchecks-url>/ping/<uid>/fail'


backends:
  hetzner:
    type: sftp
    path: storagebox:resticPhoto
    requirekey: true

  local:
    type: local
    path: /media/data/local