version: 2

locations:
  syncthing_Obsidian:
    from:
      - /media/Data01/SyncThing/Data/Obsidian-sync
    cron: '0 5 * * *'
    to: hetzner

    hooks: 
      prevalidate: 
      - 
      before:
        - 'curl -m 10 --retry 5 -X POST -H "Content-Type: text/plain" --data "Starting backup for location: ${AUTORESTIC_LOCATION}" https://<healthchecks-url>/ping/<uid>/start'
      
      success:
        - 'curl -m 10 --retry 5 -X POST -H "Content-Type: text/plain" --data "Backup successful for location: ${AUTORESTIC_LOCATION}" https://<healthchecks-url>/ping/<uid>'

      failure: 
       - 'curl -m 10 --retry 5 -X POST -H "Content-Type: text/plain" --data "Backup failed for location: ${AUTORESTIC_LOCATION}" https://<healthchecks-url>/ping/<uid>/fail'

backends:
  hetzner:
    type: sftp
    path: storagebox:syncthing
    requirekey: true